### ISSUE TITLE
Auth.proto Does Not Exist

### ISSUE THREAD

**Issue by masnwilliams** [mguay22/nestjs-grpc#1]
# Overview

When cloning this repository and running dev for each service, I run into the following error:
`[Nest] 74235  - 08/24/2023, 3:43:21 PM   ERROR [ClientProxy] ENOENT: no such file or directory, open '/nestjs-grpc/dist/apps/gateway/auth.proto'`

## Screenshots

Here is the structure of my `dist` directory:
<img width="322" alt="Screenshot 2023-08-24 at 3 49 38 PM" src="https://github.com/mguay22/nestjs-grpc/assets/43387599/fb4e10a6-f23e-4d4d-a8ad-5f591359aa44">

As it shows, there is no auth.proto in the `gateway` directory.

Any help would be appreciated as this seems to be a very simple implementation but is failing for some reason.

**Comment by sebastian-simionescu** [comment]
@mguay22 any idea what is going on ? I have the same issue

**Comment by NguyenDucDuc** [comment]
In the "gateway-app" you find the **user.module** and edit the **protoPath: ../.././auth/auth.proto**

**Comment by masnwilliams** [comment]
> In the "gateway-app" you find the **user.module** and edit the **protoPath: ../.././auth/auth.proto**

This solved my issue. @sebastian-simionescu look at this

Updating the following code in `apps/gateway/src/users/users.module.ts`

Old: `protoPath: join(__dirname, '../auth/auth.proto')`
New: `protoPath: join(__dirname, '../.././auth/auth.proto')`

**Comment by NguyenDucDuc** [comment]
@masnwilliams 
Another solution is if you don't want to fix the path of **protoPath** then you can run the command "**npm run start:dev gateway**" instead of "**npm run start:dev**"
